version: "3"
services:
  web:
    build: ./
    image: magento2-web
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - magento-sync:/var/www/html:nocopy
    depends_on:
      - db
    networks:
      - magento-network

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - magento-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - magento-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network

volumes:
  magento-sync:
    external: true
  db-data:
    driver: local

networks:
  magento-network:
    driver: bridge
