version: "3"
services:
  web:
    build: ./
    image: magento2-web
    ports:
      - "32770:80"
    links:
      - db
    volumes:
      - magento-sync:/var/www/html:nocopy
    depends_on:
      - db
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G

  db:
    image: mysql:5.7
    ports:
      - "32769:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  redis-session:
    image: redis
    ports:
      - 6379
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

volumes:
  magento-sync:
    external: true
  db-data:
    driver: local

networks:
  magento-network:
    driver: bridge
