version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-logs/mysql:/var/log/mysql

  web:
    build: ./
    image: magento2-web
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./docker-logs/apache2:/var/log/apache2
    depends_on:
      - db
volumes:
  db-data:
