version: "3"
services:
  web:
    build: ./
    image: magento2-web
    ports:
      - "32770:80"
    links:
      - db
    volumes:
      - magento-sync:/var/www/html:nocopy
    depends_on:
      - db
    networks:
      - magento-network
    platform: linux/amd64

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "32769:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - magento-network

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - magento-network

  redis-session:
    image: redis
    ports:
      - 6379
    networks:
      - magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network

  elasticsearch:
        image: elasticsearch:7.9.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node
        networks:
            - magento-network

volumes:
  magento-sync:
    external: true
  db-data:
    driver: local

networks:
  magento-network:
    driver: bridge
